### ISSUE TITLE
Comma.ai application 

### ISSUE THREAD

**Issue by xuizhang** [geohot/hammer-website#9]
Hello george, 

I have been sending you a lot of emails but you have not replied to any of them. So I am contacting you here. So i apologize in advanced. 

I am computer scientist, software engineer and a new AI scientist. I have been watching your streams and I am also a subscriber. I also liked your programing tutorial. ( Although I was not really a tutorial, as my friend who is a beginner did not understand the coding part.) 

Anyway, I had applied to comma.ai for the openings of an ML engineer.  I am just 34 years old and have learned programing two years back. For 2 years, I think I am really good. I have good people skills and analytical skills. I am a team player who loves to solve problems in groups. I was really interested in comma.ai as I truly believe that your tech can change the world and bring a positive impact on the world. 

Also check out ML work which I finished 2 days ago: https://github.com/xuizhang/advanced_ML_detection ( Guys pls give it a star) . I tried doing this problem without ML also, but kinda failed. I have realized the power of AI vs hand coded programs. I believe what you are doing is truly inspirational. 

I am also working on my blog, which will be up and online in 3 days. Do check it out. 

Also I wanted to tell you that you should start the process of visa sponsorship as I am not a US citizen. 

PS: I have also emailed to build hammer. But you have not replied to that also. I truly believe that you will give me this job as i am really passionate about AI and ML. Much more passionate than most.

**Comment by xuizhang** [comment]
also, please share your number. I want to discuss some ideas with you for comma.ai.
But you gotta sign an NDA first.

**Comment by xuizhang** [comment]
trust me dude. To be a successful businessman you gotta take chances. So take a chance on me and I wont let you down.

**Comment by tanmoyio** [comment]
@xuizhang I don’t know George will reply here or not. So I am going to tell you what I think. I have seen your source code. It’s a sequential model. Take some time to learn other things, improve your skills. Applying to comma and working with Geohot is not a regular engineering role. You should have good grasp in coding. Everyone say that they are passionate about what they are doing and that’s really great. So try improving your skills then apply at Comma. Your passion will only help you to learn those things, not to get the job. All the best you can do it.

**Comment by arindhamsharma** [comment]
@tanmoyio I have also not received any reply from these people hence contacting him on this forum.  

PS: @xuizhang I also found George on twitch, his streams are amazing.  I also watched his stream where he was mentioning some machine ( sorry i could not follow that, but liked his programming  tutorial stream ).
